### ISSUE TITLE
Enable data download and re-upload

### ISSUE THREAD

**Issue by LukasWallrich** [LukasWallrich/metaUI#11]
Users should be able to download filtered data (and configuration info) and then be able to upload a file in the same format to restore data and configuration details (to continue where they left off, and to update/change the data).

- [ ] Enable download (already partly implemented)
- [ ] Enable upload of dataset
- [ ] Enable restoration of settings

**Comment by LukasWallrich** [comment]
@LukasRoeseler download and upload should now work - feel free to take for bodypositions (at least the download, that is a quick copy-paste job)

**Comment by LukasRoeseler** [comment]
Great, thank you!
