### ISSUE TITLE
Automatically remove cases with missings (feature suggestion)

### ISSUE THREAD

**Issue by LukasRoeseler** [LukasWallrich/metaUI#20]
Can you add to the _generate_shiny_ code that missing values are deleted - maybe with a notification about the number of cases? The code didn't run for me when the dataset included entries with missing values (se, p-value).

**Comment by LukasWallrich** [comment]
Good idea - but should it rather live in the `prepare_data` (formerly `import_data`) function?

**Comment by LukasRoeseler** [comment]
Do you mean as an argument similar to use = "complete.obs" or na.rm = TRUE? I would very much like this.

**Comment by LukasWallrich** [comment]
I have now added this, with a default option to remove cases where effect size data (including se, var etc) is missing, but to keep those where metadata (e.g., on moderators) is missing ... but it can also be set to TRUE and FALSE, and then works like the usual na.rm.
