### ISSUE TITLE
Add copyright notices

### ISSUE THREAD

**Issue by LukasWallrich** [LukasWallrich/metaUI#4]
- [ ]  for psymetadata datasets
- [x]  for functions used from dmetar

**Comment by LukasWallrich** [comment]
- [ ] for Röseler et al body position code

**Comment by LukasWallrich** [comment]
@LukasRoeseler should we specifically cite your other apps as code sources? Or just have you as an author and copyright holder?

**Comment by LukasRoeseler** [comment]
@LukasWallrich I would feel more comfortable with citing the Apps that we took the code from (see below for the full references). Also, I here is code from the OpAQ-App that automatically list all loaded R-packages. It's only the names but maybe that is useful for this one, too. We can discuss this, if you want.

packages_list <- HTML(paste("<br/><br/>- ", names(sessionInfo()[["otherPkgs"]]),  sep = ""))


References:
- Röseler, L., Körner, R., & Schütz, A. (2021). Dynamic Meta-Analysis. Retrieved from https://osf.io/ns65r/
- Röseler, L., Weber, L., Helgerth, K. A. C., Stich, E., Günther, M., Tegethoff, P., Wagner, F. S., Ambrus, E., Antunovic, M., Barrera, F., Halali, E., Ioannidis, K., McKay, R., Milstein, N., Molden, D. C., Papenmeier, F., Rinn, R., Schreiter, M. L., Zimdahl, M., Allen, E., Bahník, S., Baumeister, R. F., Bermeitinger, C., Bickenbach, S. L. C., Blank, P. A., Blower, F. B. N., Bögler, H. L., Boo, F. L., Boruchowicz, C., Bühler, R. L., Burgmer, P., Cheek, N., N., Dohle, S., Dorsch, L., Dück, M. S., Fels, S.-A., Fischer, A. L., Frech, M.-L., Freira, L., Friedinger, K., Genschow, O., Harris, A., Hartig, B., Häusser, J. A., Hedgebeth, M., Henkel, M., Horvath, D., Hügel, J. C., Igna, E. L. E., Imhoff, R., Intelmann, P., Karg, A. H., Klamar, A., Klein, C., Klusmann, B., Knappe, E., Köppel, L.-M., Koßmann, L., Kraft, P., Kroworsch, M. K., Krueger, S. M., Kühling, S., Lagator, S., Lammers, J., Loschelder, D. D., Navajas, J., Norem, J., K., Novak, J. Onuki, Y., Page, E., Panse, F., Pavlovic, Z., Pearton, J., Rebholz, T. R., Rodgers, S., Röseler, J. J., Rostekova, A., Roßmaier, K. V., Sartorio, M., Scheelje, L., Schindler, S., Schreiner, N. B., Seida, C., Shanks, D. R., Siems, M.-C., Stitz, M., Starkulla, M., Stäglich, M., Thies, K., Thum, E., Undorf, M., Unger, B. D., Urlichich, D., Vadillo, M. A., Wackershauser-Sablotny, V., Wessel, I., Wolf, H., Zhou, A., & Schütz, A. (2022). OpAQ: Open Anchoring Quest, Version 1.1.48.95. https://dx.doi.org/10.17605/OSF.IO/YGNVB

**Comment by LukasWallrich** [comment]
Thanks - we would not cite other packages within the package itself, but could add that to the Shiny about page? Your code there would not work here because we do not load the packages here (to avoid namespace conflicts, I am referring to each function with the pkg::fun() syntax) - but the following works `req_packages <- pacman::p_depends("metaUI", local = TRUE) %>% purrr::pluck("Imports")`

I am happy to add these citations to the README, and thus to the package webpage. However, do you think all of the authors needs to be listed as *code* copyright holders in DESCRIPTION (especially for the tiny OpAQ snippet we used)? Or was the code itself just your work?

**Comment by LukasRoeseler** [comment]
I see, yes all of the code that we took was written by me. None of the other authors need to be listed as code copyright holders.
